# Sample benchmark config
# Runs a test matrix of [device x test x models x precisions x test_args]
# Currently, `summarize.py` only supports sinxxgle device and single test
# The first combination will be used as the baseline
# In this example, baseline is ("cuda", "eval", "fp32")
device:
  - "cpu"
test:
  - "eval"
models:
  - "alexnet"
  - "attention_is_all_you_need_pytorch"
  - "hf_Bert"
  - "nvidia_deeprecommender"
  - "resnet18"
precision:
  - "fp32"
args:
  # script based
  - "--backend blade"
