# Sample benchmark config
# Runs a test matrix of [device x test x models x precisions x test_args]
# Currently, `summarize.py` only supports sinxxgle device and single test
# The first combination will be used as the baseline
# In this example, baseline is ("cuda", "eval", "fp32")
device:
  - "cpu"
test:
  - "eval"
precision:
  - "fp32"
args:
  # torchdynamo based
  - "--torchdynamo ofi"
