# Sample benchmark config
# Runs a test matrix of [device x test x models x precisions x test_args]
# Currently, `summarize.py` only supports sinxxgle device and single test
# The first combination will be used as the baseline
# In this example, baseline is ("cuda", "eval", "fp32")
device:
  - "cuda"
test:
  - "eval"
precision:
  - "fp32"
args:
  # empty argument means the default pytorch eager mode
  - ""
  # script based
  - "--backend blade"
  - "--backend blade --trt"
  - "--backend torchscript --no-ofi"

  # torchdynamo based
  - "--torchdynamo eager"
  - "--torchdynamo ts_nvfuser"
  - "--torchdynamo blade_optimize_dynamo"
  - "--torchdynamo blade_optimize_dynamo --trt"
  - "--torchdynamo inductor"
