name: TorchBench Benchmarking
on:
  workflow_dispatch:
    inputs:
      userbenchmark_name:
        description: "Name of the user benchmark to run"
        required: true
env:
  PYTHON_VERSION: "3.8"
  TENSORRT_PYTHON_VERSION: "cp38"
  TENSORRT_VERSION: "8.2.4.2"
  CUDA_VERSION: "cu113"
  CONDA_ENV_NAME: "backends-ci"
  MAGMA_VERSION: "magma-cuda113"
  SETUP_SCRIPT: "/data/shared/setup_instance.sh"
jobs:
  run-benchmark:
    runs-on: [self-hosted, a100-runner]